// Generated by CoffeeScript 2.2.1
angular.module('ngLocalStorage', []).factory('$localStorage', [
  '$window',
  function($window) {
    return {
      set: function(key,
  value) {
        $window.localStorage[key] = JSON.stringify(value);
      },
      get: function(key) {
        return JSON.parse($window.localStorage[key] || null);
      },
      delete: function(key) {
        $window.localStorage.removeItem(key);
      }
    };
  }
]);
